---
title: "Homework 5"
author: "Vincent Tam"
date: "November 3, 2018"
output: github_document
---

```{r Problem 1, setup, echo = FALSE, message = FALSE, warning = FALSE, error = FALSE}
library(tidyverse, rvest)
library(janitor)
library(dplyr, purrr, ggplot)
library(data.table)
conexp = data_frame(ArmID = list.files(path = "data")) %>%
  mutate(ArmID = as.character(ArmID)) %>%
  mutate(ArmID = str_replace(ArmID, ".csv", "")) %>%
  mutate(ArmID = str_replace(ArmID, "_", ""))
data = map(list.files(path = "data", full.names = TRUE), read_csv, col_names = TRUE) 
data = bind_rows(data, .id = NULL) 
complete = bind_cols(conexp, data) %>%
  clean_names() 
names(complete) <- gsub("\\_", "", names(complete))
complete
gather(complete, key = week, value = obs, week1:week8) %>%
ggplot(aes(week, obs, color = armid, group = armid)) + geom_point() + geom_line() + labs(title = "Control vs Experimental, Week 1-8", x = "Week", y = "Observations")
```
```{r Problem 2}
library(dplyr)
library(janitor)
library(purrr)
library(broom)
library(reshape)
library(knitr)
library(reshape2)
library(tidyverse)
library(ggplot2)
library(revest)
library(stringr)
hom_data <- read.csv(url("https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv"))
hom_data = 
  hom_data %>%
  mutate(city_state = str_c(city, ",", state))
dispo = 
  hom_data %>%
  select(city_state, disposition) %>%
  group_by(city_state) %>%
  summarize(total = n())
solved =
  hom_data %>%
  filter(disposition == "Closed by arrest") %>%
  group_by(city_state) %>%
  summarize(total_solved = n())
unsolved =
  hom_data %>%
  filter(disposition == "Closed without arrest" | disposition == "Open/No arrest") %>%
  group_by(city_state) %>%
  summarize(total_unsolved = n())
## prop test for Baltimore, MD
baltimore_total =
  dispo %>%
  filter(city_state == "Baltimore,MD") 
baltimore_solved =
  solved %>%
  filter(city_state == "Baltimore,MD")
baltimore_unsolved = 
  unsolved %>%
  filter(city_state == "Baltimore,MD") 
baltimore_merged = 
  merge(baltimore_unsolved, baltimore_total)
baltimore_proptest = 
  prop.test(baltimore_merged$total_unsolved, baltimore_merged$total) %>%
  tidy() %>%
  select(conf.low, conf.high, estimate) %>%
  kable(digits = 3)
baltimore_proptest
## prop.test = unsolved/total
partial_table = 
  merge(dispo, unsolved, by = "city_state", na.rm = TRUE, all = T) %>%
  filter(city_state != "Tulsa,AL")
partial_table = as.data.frame(partial_table)
allcities_proptest = 
  partial_table %>%
  mutate(homicide_CI = map2(.x = total_unsolved, .y = total, ~prop.test(x = .x, n = .y)$conf.int)) %>%
  mutate(homicide_estimate = map2(.x = total_unsolved, .y = total, ~prop.test(x = .x, n = .y)$estimate)) %>%


  unnest()

plot_cities = 
  allcities_proptest %>%
  ggplot(aes(city_state, homicide_estimate, color = city_state, group = city_state)) + geom_point() + geom_line()
plot_cities

na.omit(partial_table) %>%
  
broom::tidy(allcities_proptest) 
  select(estimate, conf.low, conf.high) %>%
  
map_chr(allcities_proptest, typeof) %>% table()
  unnest(allcities_proptest, homicide_prop, .drop = FALSE)
allcities_proptest
plot_cities =
  allcities_proptest %>% 
  ggplot(aes(fct_reorder(city_state, homicide_estimate), homicide_estimate)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high)) +
  labs(
    title = "Estimates and CIs for All Cities",
    x = "City",
    y = "Estimates"
  )  +
  theme(axis.text.x = element_text(angle = 90)) 
plot_cities

```


